apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-web-app
  name: node-web-app-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: node-web-app
  type: NodePort
